x-common-dns: &common-dns
  dns: ${LC_COMPOSE_NAMESERVER}
  dns_search: ${LC_COMPOSE_CLUSTER}.local
  dns_opt: [ 'ndots:1' ]
x-common-network: &common-network
  networks:
    - common
x-common-restart: &common-restart
  restart: on-failure
x-graceful-stop: &graceful-stop
  stop_grace_period: 1m
  stop_signal: SIGINT

services:
  ide:
    image: ${LC_COMPOSE_IMAGE}:${LC_COMPOSE_IMAGE_TAG}
    command: [
      "node", "./src/server/server.js"
    ] 
    ports:
      - ${LC_COMPOSE_IPADDR}:${LC_COMPOSE_WEB_PORT}:${LC_COMPOSE_WEB_PORT}
    environment:
      - NODE_ENV=${LC_COMPOSE_NODE_ENV}
      - PORT=${LC_COMPOSE_WEB_PORT}
      - DB_HOST=${LC_COMPOSE_MYSQL_HOST}
      - DB_NAME=${LC_COMPOSE_MYSQL_NAME}
      - DB_USER=${LC_COMPOSE_MYSQL_USER}
      - DB_PASSWORD=${LC_COMPOSE_MYSQL_PASSWORD}
      - DB_PORT=${LC_COMPOSE_MYSQL_PORT}
      - REDIS_HOST=${LC_COMPOSE_REDIS_HOST}
      - REDIS_PORT=${LC_COMPOSE_REDIS_PORT}
      - REDIS_DB=${LC_COMPOSE_REDIS_DB}
      - BACKEND_URL=${LC_COMPOSE_BACKEND_URL}
      - IDE_URL=${LC_COMPOSE_IDE_URL}
      - REACT_APP_IDE_URL=${LC_COMPOSE_REACT_APP_IDE_URL}
      - PUBLIC_URL=${LC_COMPOSE_PUBLIC_URL}
    <<: *graceful-stop
    <<: *common-dns
    <<: *common-network
    <<: *common-restart


networks:
  common:
    external: ${LC_COMPOSE_NETWORK_EXTERNAL:-false}
    name: "${LC_COMPOSE_NETWORK_ID:-bridge-lan}"
