x-common-dns: &common-dns
  dns: ${LC_COMPOSE_NAMESERVER}
  dns_search: ${LC_COMPOSE_CLUSTER}.local
  dns_opt: [ 'ndots:1' ]
x-common-network: &common-network
  networks:
    - common
x-common-restart: &common-restart
  restart: on-failure
x-graceful-stop: &graceful-stop
  stop_grace_period: 1m
  stop_signal: SIGINT

services:
  runtime-config:
    image: alpine
    entrypoint: ["/bin/sh","-c"]
    command:
    - |
       . /app/scripts/apply_env.sh
    environment:
      - WEB_PORT: ${LC_COMPOSE__WEB_PORT}
    volumes:
      - ./scripts:/app/scripts
      - ./config:/config-source
      - ./config-runtime:/config-destination
    <<: *common-network
  nginx:
    image: nginx:1.22-alpine
    volumes:
      - ide-public:/var/www/public
      - ./config-runtime/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${LC_COMPOSE_NODE_WEB_PORT}:80
    depends_on:
      runtime-config:
        condition: service_completed_successfully
    <<: *common-network
    <<: *common-dns
    <<: *common-restart
    <<: *common-logging
  ide:
    image: ${LC_COMPOSE_IMAGE}:${LC_COMPOSE_IMAGE_TAG}
    command: [
      "node", "./src/server/server.js"
    ] 
    volumes:
      - ide-public:/app/public
    ports:
      - ${LC_COMPOSE_IPADDR}:${LC_COMPOSE_WEB_PORT}:${LC_COMPOSE_WEB_PORT}
    environment:
      - NODE_ENV=${LC_COMPOSE_NODE_ENV}
      - PORT=${LC_COMPOSE_WEB_PORT}
      - DB_HOST=${LC_COMPOSE_MYSQL_HOST}
      - DB_NAME=${LC_COMPOSE_MYSQL_DATABASE}
      - DB_USER=${LC_COMPOSE_MYSQL_USER}
      - DB_PASSWORD=${LC_COMPOSE_MYSQL_PASSWORD}
      - DB_PORT=${LC_COMPOSE_MYSQL_PORT}
      - REDIS_HOST=${LC_COMPOSE_REDIS_HOST}
      - REDIS_PORT=${LC_COMPOSE_REDIS_PORT}
      - REDIS_DB=${LC_COMPOSE_REDIS_DB}
      - GRAPHQL_ADMIN_URL=${LC_COMPOSE_GRAPHQL_ADMIN_URL}
      - GRAPHQL_LEGACY_URL=${LC_COMPOSE_GRAPHQL_LEGACY_URL}
      - GRAPHQL_URL=${LC_COMPOSE_GRAPHQL_URL}
    depends_on:
      - nginx
    <<: *graceful-stop
    <<: *common-dns
    <<: *common-network
    <<: *common-restart


networks:
  common:
    external: ${LC_COMPOSE_NETWORK_EXTERNAL:-false}
    name: "${LC_COMPOSE_NETWORK_ID:-bridge-lan}"

volumes:
  ide-public:
